#!/bin/bash
set -euo pipefail
set -x

export SKYSCRAPER_HOME="$(cd "$(dirname "$0")/.." && pwd)"

cleanup() {
   mv VERSION.bk VERSION || true
}

cleanup

run_termux_docker() {
   local -r arch="$1"

   TERMUX_PKG_NAME="skyscraper"
   TERMUX_PKG_BIN_NAME="Skyscraper"

   cd "$SKYSCRAPER_HOME"

   git clone https://github.com/termux/termux-packages --depth 1
   git clone https://github.com/termux/x11-packages --depth 1 || true

   mv termux-packages/packages .
   mv x11-packages/packages/* ./packages || true

   mkdir -p "./packages/${TERMUX_PKG_NAME}" || true
   cp "./scripts/build.sh" "./packages/${TERMUX_PKG_NAME}"
   ls -la "./packages/${TERMUX_PKG_NAME}"

   "./termux-packages/scripts/run-docker.sh" ./build-package.sh -a "$arch" "$TERMUX_PKG_NAME"

   rm -rf target || true
   mkdir -p target || true
   docker cp "termux-package-builder:/data/data/com.termux/files/usr/bin/${TERMUX_PKG_BIN_NAME}" "target"
}

build() {
   source "VERSION"
   LATEST="$VERSION"

   if [[ "$OSTYPE" == "darwin"* ]]; then
      mv VERSION VERSION.bk || true
   fi

   cd "$SKYSCRAPER_HOME"
   echo "--- Cleaning out old build if one exists ---"
   make --ignore-errors clean || true
   rm --force .qmake.stash || true
   qmake
   echo "--- Building Skyscraper v.$LATEST ---"
   make "-j$(nproc)"
   echo "--- Installing Skyscraper v.$LATEST ---"
   sudo make install
   echo "--- Skyscraper has been updated to v.$LATEST ---"
}

main() {
   case "${1:-}" in
      "android_aarch64") run_termux_docker "aarch64" ;;
      *) build ;;
   esac
}

trap cleanup EXIT
main "$@"
