#!/bin/bash
set -euo pipefail
set -x

export SKYSCRAPER_HOME="$(cd "$(dirname "$0")/.." && pwd)"

cleanup() {
   mv VERSION.bk VERSION || true
}

cleanup
source "VERSION"
LATEST="$VERSION"

if [[ "$OSTYPE" == "darwin"* ]]; then
    mv VERSION VERSION.bk || true
fi

build() {
    cd "$SKYSCRAPER_HOME"
    echo "--- Cleaning out old build if one exists ---"
    make --ignore-errors clean || true
    rm --force .qmake.stash || true
    qmake
    echo "--- Building Skyscraper v.$LATEST ---"
    make "-j$(nproc)"
    echo "--- Installing Skyscraper v.$LATEST ---"
    sudo make install
    echo "--- Skyscraper has been updated to v.$LATEST ---"
}

main() {
    build
}

trap cleanup EXIT
main