#!/bin/bash
set -euo pipefail
set -x

export SKYSCRAPER_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${SKYSCRAPER_HOME}/scripts/core.sh"

_test_android() {
   file "${SKYSCRAPER_HOME}/target/Skyscraper" | grep "$1"
}

main() {
   case "${1:-}" in
      "android-aarch64") _test_android "aarch64";;
      "android-arm") _test_android "arm" ;;
      *) Skyscraper -h | grep 'modded by' ;;
   esac
}

main "$@"