#!/bin/bash
set -euo pipefail
set -x

export SKYSCRAPER_HOME="$(cd "$(dirname "$0")/.." && pwd)"

main() {
  local -r target="${SKYSCRAPER_HOME}/target"
  mkdir -p "$target" || true
   
  local bin="Skyscraper"
  if command -v Skyscraper; then
    bin="$(which Skyscraper)"
  fi

  sudo cp "$bin" "${target}/Skyscraper"

  cd "$target"
  ls -la .
  tar -czf skyscraper.tar.gz *
  ls -la .
}

main