name: Tests

on: [push]

jobs:
  TermuxTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build
        run: ./scripts/install android-aarch64
      - name: Test
        run: file target/Skyscraper
