name: Tests

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install deps
        run: ./scripts/deps
      - name: Build
        run: ./scripts/install
      - name: Test
        run: ./scripts/test
      - name: (WIP) Zip
        run: ./scripts/zip
  TermuxText:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build
        run: ./scripts/install-termux
      - name: Test
        run: file out/Skyscraper
